---

- name: Waiting for port | "{{ PortNumber }}" | to be | "{{ PortStatus }}"
  wait_for:
    host: "{{ ansible_host }}"
    port: "{{ PortNumber }}"
    state: "{{ PortStatus }}"
    timeout: 300
    delay: 10
