---

- hosts: clusterNodes
  gather_facts: false
  tasks:
    - name: Removing Old zookeeper files | {{ zookeeperInstallDir }}/zookeeper-{{ zookeeperOldVersion }}
      ansible.builtin.file:
        path: "{{ zookeeperInstallDir }}/zookeeper-{{ zookeeperOldVersion }}"
        state: absent
      when:
        - zookeeperOldVersion is defined
        - zookeeperOldVersion is version(zookeeperVersion, '!=')