---

- hosts: clusterNodes
  gather_facts: true
  become: true
  tasks:
    - name: mount ebs volume
      ansible.builtin.include_role:
        name: common
        tasks_from: ebsDisk.yml

    - name: install & configure cloudwatch logs agent
      ansible.builtin.include_role:
        name: cloudwatch
    
    - name: install python3* packages and other dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop:
        - python3
        - python3-pip
        - python3-devel
        - gcc
        - amazon-linux-extras
