---

- hosts: clusterNodes:clusterAddNodes
  gather_facts: true
  serial: 1
  tasks:
    - name: including restart tasks
      import_role:
        name: serviceState
      vars:
        serviceName: zookeeper
        serviceState: restarted

    - name: zookeeper port status
      include_role:
        name: portCheck
      vars:
        PortNumber: "{{ item }}"
        PortStatus: started
      loop:
        - "{{ zookeeperClientPort }}"