---

- hosts: clusterNodes
  gather_facts: true
  serial: 1
  tasks:
    - ansible.builtin.include_role:
        name: configure
        tasks_from: dynamicConfigs
      vars:
        - zookeeperConfigFile: log4j.properties
  
    - name: restarting all nodes
      ansible.builtin.import_role:
        name: serviceState
      vars:
        serviceName: zookeeper
        serviceState: restarted
      when: configStatus.changed

    - name: zookeeper port status
      ansible.builtin.include_role:
        name: portCheck
      vars:
        PortNumber: "{{ item }}"
        PortStatus: started
      loop:
        - "{{ zookeeperStoragePort }}"
        - "{{ zookeeperNativeTransportPort }}"
      when: configStatus.changed