---

- hosts: clusterNodes
  gather_facts: true
  tasks:
    - name: make sure gather facts is triggered on all nodes required for zoo.cfg
      ansible.builtin.debug:
        var: ansible_fqdn

- hosts: clusterNodes
  gather_facts: true
  serial: 1
  tasks:
    - ansible.builtin.include_role:
        name: configure
        tasks_from: dynamicConfigs

    - name: Restarting all nodes
      ansible.builtin.import_role:
        name: serviceState
      vars:
        serviceName: zookeeper
        serviceState: restarted
      when: configStatus.changed

    - name: zookeeper port status
      ansible.builtin.include_role:
        name: portCheck
      vars:
        PortNumber: "{{ item }}"
        PortStatus: started
      loop:
        - "{{ zookeeperClientPort }}"
      when: configStatus.changed