---

- hosts: clusterNodes
  gather_facts: true
  become: true
  pre_tasks:
    - name: Including system upgrade role
      ansible.builtin.import_role:
        name: systemUpgrade
      when: systemUpgradeRequired

    - name: Including java role
      ansible.builtin.import_role:
        name: java

  roles:
    - common
    - install
    - configure
    - service

- hosts: clusterNodes
  gather_facts: false
  become: true
  serial: 1
  tasks:
    - name: Starting all nodes
      ansible.builtin.import_role:
        name: serviceState
      vars:
        serviceName: zookeeper
        serviceState: started

    - name: zookeeper Port Status
      ansible.builtin.include_role:
        name: portCheck
      vars:
        PortNumber: "{{ item }}"
        PortStatus: started
      loop:
        - "{{ zookeeperClientPort }}"