---

- hosts: clusterNodes
  gather_facts: true
  become: true
  roles:
    - java
    - common

- hosts: clusterNodes
  gather_facts: true
  become: true
  tasks:
    - name: installing latest version of Zookeeper
      ansible.builtin.import_role:
        name: install
        tasks_from: download

    - name: configuring latest Zookeeper version
      ansible.builtin.import_role:
        name: configure

- hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Switching zookeeper Version to {{ zookeeperVersion }} on all nodes (Rolling fashion)
      ansible.builtin.pause:
        prompt: "Press enter to confirm or ctrl-c to cancel"

- hosts: clusterNodes
  gather_facts: false
  become: true
  serial: 1
  tasks:
    - name: switching Zookeeper version to {{ zookeeperVersion }}
      ansible.builtin.import_role:
        name: install
        tasks_from: createSymlink

    - name: restarting all nodes
      ansible.builtin.import_role:
        name: serviceState
      vars:
        serviceName: zookeeper
        serviceState: restarted

    - name: zookeeper Port Status
      ansible.builtin.include_role:
        name: portCheck
      vars:
        PortNumber: "{{ item }}"
        PortStatus: started
      loop:
        - "{{ zookeeperClientPort }}"
