---

- name: copying zooki.py to {{ zookeeperInstallDir }}
  copy:
    src: zooki.py
    dest: "{{ zookeeperInstallDir }}"
    owner: "{{ zookeeperUser }}"
    group: "{{ zookeeperGroup }}"
    mode: 0777

- name: cron for zookeeper metric collector ( zooki.py )
  cron:
    name: "zookeeper metric collector"
    minute: "*"
    hour: "*"
    weekday: "*"
    user: root
    job: 'find /bin/ -name "python3*m" -print0 -exec {} {{ zookeeperInstallDir }}/zooki.py {{ zookeeperInstallDir }} {{ zookeeperLogDir }}/  {{ zookeeperEnvironment }} \;'