---

- name: system upgrade | RedHat
  yum:
    name: "*"
    state: latest
    update_cache: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- block:

    - name: system upgrade | Debian
      apt:
        upgrade: dist
        update_cache: true

    - name: removing unused packages | Debian
      apt:
        autoclean: true
        autoremove: true

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'