---
- name: Creating zookeeper configurations | {{ zookeeperConfigFile }}
  ansible.builtin.template:
    src: "{{ zookeeperConfigFile }}"
    dest: "{{ zookeeperInstallDir }}/zookeeper-{{ zookeeperVersion }}/conf/{{ zookeeperConfigFile }}"
    owner: "{{ zookeeperUser }}"
    group: "{{ zookeeperGroup }}"
  register: configStatus