---
zookeeper_install_dir: /opt/zookeeper
zookeeper_data_dir: /var/lib/zookeeper
zookeeper_client_port: 2181
zookeeper_tick_time: 2000
zookeeper_init_limit: 5
zookeeper_sync_limit: 2
zookeeper_log_dir: /var/log
zookeeper_user: root
zookeeper_group: root
# latest stable
zookeeper_version: 3.4.10
