---

- name: creating zookeeper group
  group:
    name: "{{  zookeeperGroup }}"
    gid: "{{ zookeeperGroupId }}"
    state: present

- name: creating zookeeper user
  user:
    name: "{{ zookeeperUser }}"
    comment: zookeeper Default User
    uid: "{{ zookeeperUserId }}"
    group: "{{ zookeeperGroup }}"