---

# TODO: download zookeeper tar file to ansible server only if possible 
#       to reduce multiple downloads on all nodes.
#       Not Required: if downloading from local company mirror.

- name: Copying and Unarchive zookeeper tar | {{ zookeeperVersion }}
  ansible.builtin.unarchive:
    src: "{{ zookeeperTarLocation }}"
    dest: "{{ zookeeperInstallDir }}/zookeeper-{{ zookeeperVersion }}"
    owner: "{{ zookeeperUser }}"
    group: "{{ zookeeperGroup }}"
    validate_certs: false
    keep_newer: yes
    extra_opts: ["--strip-components=1"]
    creates: "{{ zookeeperInstallDir }}/zookeeper-{{ zookeeperVersion }}/bin"

- name: Ensuring permissions on unarchieved files
  ansible.builtin.file:
    path: "{{ zookeeperInstallDir }}/zookeeper-{{ zookeeperVersion }}"
    owner: "{{ zookeeperUser }}"
    group: "{{ zookeeperGroup }}"
    recurse: true
    mode: 0775